Bloggie/Pages/Admin/Blogs/Add.cshtml.cs
using Bloggie.Data;
using Bloggie.Enums;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    public class AddModel : PageModel
    {


        // private readonly BloggieDbContext bloggieDbContext;

        //public AddModel(BloggieDbContext bloggieDbContext)
        //{
        //    this.bloggieDbContext = bloggieDbContext;
        //}// injecting DbContext , so that we can access the database

        //As we have injected the IBlogPostRepository service  in the program.cs file we now no longer need to inject dbcontext here so commenting the above  part and injecting the 
        //IBlogPostRepository below

        private readonly IBlogPostRepository blogPostRepository;
        public AddModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        //[BindProperty]
        //public string Heading { get; set; }
        //[BindProperty]
        //public string Title { get; set; }

        //Instead of doing the above for  each and every property , what we did is we creted a class named AddBlogPost in which we have defined each and every property

        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }

        [BindProperty]
        public IFormFile FeaturedImage { get; set; }

        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPost() 
        {
            // var heading = Request.Form["heading"];//by this manner we can  directly access the the form data that was submitted via an HTTP POST request, but we will not
            //use this direct access method as it manual and has many drawbacks,So we did the above method(comment ), see the e-notes I have mentioned there in details 

            BlogPost blogPost = new BlogPost
            {
                Heading = AddBlogPostRequest.Heading,
                PageTitle = AddBlogPostRequest.PageTitle,
                Content = AddBlogPostRequest.Content,
                ShortDescription = AddBlogPostRequest.ShortDescription,
                FeaturedImageUrl = AddBlogPostRequest.FeaturedImageUrl,
                UrlHandle = AddBlogPostRequest.UrlHandle,
                PublishedDate = AddBlogPostRequest.PublishedDate,
                Author = AddBlogPostRequest.Author,
                Visible = AddBlogPostRequest.Visible,
            };


            //await bloggieDbContext.BlogPosts.AddAsync(blogPost);
            //await bloggieDbContext.SaveChangesAsync();

            // commenting the above part as we no longer need DbContext , below is the replacement of the above part as we have injected the IBlogPostRepository 

           await blogPostRepository.AddAsync(blogPost);
            //TempData["MessageDescription"] = "New Blog Post Created !";
            var notification = new Notification
            {
                Message = "New Blog Post Created !",
                Type = NotificationType.Success
            };
            TempData["Notification"] = JsonSerializer.Serialize(notification);
            return RedirectToPage("/Admin/Blogs/List");
        }
    }
}

Bloggie/Pages/Admin/Blogs/Edit.cshtml.cs
using Bloggie.Data;
using Bloggie.Enums;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    public class EditModel : PageModel
    {


        //private readonly BloggieDbContext _db;

        //public EditModel(BloggieDbContext db)
        //{
        //    _db = db;
        //}

        private readonly IBlogPostRepository blogPostRepository;
        public EditModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        [BindProperty]
        public BlogPost BlogPost { get; set; }

        [BindProperty]
        public IFormFile FeaturedImage { get; set; }

        public async Task OnGet(Guid id)  // this was intially public void OnGet , see when convert to async then if the method is IAction than write that
                                          // method inside Task , the general notation is async Task<return type method (say IActionResult)>, if the return type 
                                          //of method is void than write like this  public async Task OnGet
        {
           // BlogPost = await _db.BlogPosts.FindAsync(id);
            BlogPost = await blogPostRepository.GetAsync(id);
        }

        public async Task< IActionResult> OnPostEdit() 
        {
            //var existingBlogPost = await _db.BlogPosts.FindAsync(BlogPost.Id);
            //if (existingBlogPost != null)
            //{
            //    existingBlogPost.Heading = BlogPost.Heading;
            //    existingBlogPost.PageTitle = BlogPost.PageTitle;
            //    existingBlogPost.Content = BlogPost.Content;
            //    existingBlogPost.FeaturedImageUrl = BlogPost.FeaturedImageUrl;
            //    existingBlogPost.Author = BlogPost.Author;
            //    existingBlogPost.PublishedDate = BlogPost.PublishedDate;
            //    existingBlogPost.Visible = BlogPost.Visible;
            //    existingBlogPost.ShortDescription = BlogPost.ShortDescription;
            //    existingBlogPost.UrlHandle = BlogPost.UrlHandle;

            //}

            //    //you can also use update to do the same above functionality, but you if use this than it will break when id is invalid , in this case BlogPost will be null and thus it will throw error while updating
            //    //_db.BlogPosts.Update(BlogPost); 

            //  await  _db.SaveChangesAsync();

            try
            {
                //throw new Exception();

                await blogPostRepository.UpdateAsync(BlogPost);

                //ViewData["Message Description"] = "Record was successfully saved";
                ViewData["Notification"] = new Notification
                {
                    Type = NotificationType.Success,
                    Message = "Record was successfully saved"

                };
   
    }
            catch (Exception ex)
            {
                ViewData["Notification"] = new Notification
                {
                    Type = NotificationType.Error,
                    Message = "Something went wrong"

                };
               

            };
            return Page();

           // return RedirectToPage("/Admin/Blogs/List");
        }

        public async Task<IActionResult> OnPostDelete() 
        {
            //var existingBlogPost = await _db.BlogPosts.FindAsync(BlogPost.Id);
            //if (existingBlogPost != null) 
            //{
            //     _db.BlogPosts.Remove(existingBlogPost);
            //   await _db.SaveChangesAsync();
            //    return RedirectToPage("/Admin/Blogs/List");
            //}

            var result = await blogPostRepository.DeleteAsync(BlogPost.Id);
            if (result == true)
            {
               var notification = new Notification
                {
                    Message = "Blog Post deleted successfully",
                    Type = NotificationType.Success,
                };

                TempData["Notification"] = JsonSerializer.Serialize(notification);

                return RedirectToPage("/Admin/Blogs/List");
            }
            
           


            return Page();
        }
    }
}

Bloggie/Pages/Admin/Blogs/List.cshtml.cs
using Bloggie.Data;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    
    public class ListModel : PageModel
    {
        //private readonly BloggieDbContext bloggieDbContext;

        //public ListModel(BloggieDbContext bloggieDbContext)
        //{
        //    this.bloggieDbContext = bloggieDbContext;
        //}

        private readonly IBlogPostRepository blogPostRepository;
        public ListModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        public List<BlogPost> BlogPosts { get; set; }
        public async Task OnGet()
        {
            //BlogPosts =await bloggieDbContext.BlogPosts.ToListAsync();
            //var a= BlogPosts[0].Id; // In case you want to access here only 
            //var b = BlogPosts[0].Heading;

            //

            // var messageDescription = (string) TempData["MessageDescription"];
            var notificationJson = (String) TempData["Notification"];
            //if (!string.IsNullOrEmpty(messageDescription)) 
            //{
            //    ViewData["MessageDescription"]= messageDescription;
            //}
            if (notificationJson != null) 
            {
                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson.ToString());


            }

            BlogPosts = (await blogPostRepository.GetAllAsync())?.ToList();// you can also use BlogPosts =(List<BlogPost>) await  blogPostRepository.GetAllAsync();
                                                                            //to explicitly cast IEnumerable to List
        }

    }
}

Bloggie/Pages/Admin/Blogs/trial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bloggie.Pages.Admin.Blogs
{
    public class trialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bloggie/Pages/Blog/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Bloggie.Repositories;
using Bloggie.Models.Domain;


namespace Bloggie.Pages.Blog
{
    public class DetailsModel : PageModel
    {
		private readonly IBlogPostRepository blogRepository;

        public BlogPost BlogPost { get; set; }
		public DetailsModel(IBlogPostRepository blogRepository)
        {
			this.blogRepository = blogRepository;
		}
        public async Task OnGet(string urlHandle)
        {
          BlogPost= await blogRepository.GetAsync(urlHandle);
        }
    }
}

Bloggie/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Pages.Admin.Blogs.AddModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
	<div class="container">
		<h1>Add Blog Post</h1>
	</div>
</div>

<div>
	<div class="container">
          <form method="post">
                    <div class="mb-3">
                        <label for="heading" class="form-label">Heading</label>
                        <input type="text"  class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading">
                      @*  if you are using direct access method than here you need to specify the name property, if you are using asp-for tag than
                          donot use name property with it as asp-for tag  by default generates name and id field, so if you are using 
                          name field along with the asp-for tag than the name attribute generated by asp-for tag will be over ridden by the name attribute
                          that you explicitly gave due to which binding will not happen and during execution of code the Heading value will come nulls

                id Attribute: Used for client-side purposes and does not affect server-side model binding. Overriding it does not cause issues with model binding.so explicitly Id use karne pe 
                ya kuch problem nahi aa rahi 
                *@
                    </div>
                    <div class="mb-3">
                        <label for="pageTitle" class="form-label">Page Title</label>
                        <input type="text"  class="form-control" id="pageTitle" asp-for="AddBlogPostRequest.PageTitle">
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">Content</label>
                        <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"></textarea>
                    </div>
                    <div class="mb-3">
                            <label for="Short Description" class="form-label">Short Description</label>
                            <input type="text" class="form-control" id="Short Description" asp-for="AddBlogPostRequest.ShortDescription">
                    </div>


                    <div class="mb-3">
                        <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
                        <input type="file" id="featuredImageUpload" asp-for="FeaturedImage">
                          <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />
                    </div>

                    <div class="mb-3">
                        <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                        <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeaturedImageUrl">
                    </div>

                    <div class="mb-3">
                        <label for="urlHandle" class="form-label">Url Handle</label>
                        <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle">
                    </div>
                    <div class="mb-3">
                        <label for="publishedDate" class="form-label">Published Date</label>
                        <input type="date" class="form-control" id="publishedDate" asp-for="AddBlogPostRequest.PublishedDate">
                    </div>
                    <div class="mb-3">
                        <label for="author" class="form-label">Author</label>
                        <input type="text" class="form-control" id="author" asp-for="AddBlogPostRequest.Author">
                    </div>
                    <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                        <label class="form-check-label" for="isVisible">
                            Is Visible
                        </label>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
          </form>   
    </div>
</div>
@section Scripts {
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/image'
        });
        const featuredImageUploadElement = document.getElementById("featuredImageUpload");
        const featuredImageUrl = document.getElementById('featuredImageUrl');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay');

        async function uploadFeatureImage(e) 
        {

            console.log(e.target.files[0]);
            let data = new FormData();
            data.append('file', e.target.files[0]);
            await fetch('/api/image', {
                method: 'POST',
                headers: {
                    Accept: '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => { 
                    featuredImageUrl.value = result.link;
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link;
                } );
        }
        featuredImageUploadElement.addEventListener('change', uploadFeatureImage);
        console.log("this is outside");
    </script>
} 

Bloggie/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model Bloggie.Pages.Admin.Blogs.EditModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
	<div class="container">
		<h1>Edit Blog Post</h1>
	</div>
</div>


@* @{
    var messageDescription = (string)ViewData["Message Description"];
    // since viewData is of object type we are converting it explicitly to string type so that we
    //easily check whether it is null or empty bystring.IsNullOrEmpty
}

@if (!string.IsNullOrEmpty(messageDescription))
{
    <div class="alert alert-success alert-dismissible fade show mb-5" role="alert">
        @Html.Raw(messageDescription)
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
} *@

@* repalcing the above html portion by partial view _Notification.cshtml *@

<partial name="_Notification" for="ViewData" />

@if (Model.BlogPost != null)
{
    <div>
        <div class="container">
            <form method="post">
                <div class="mb-3">
                    <label for="heading" class="form-label">Id</label>
                    <input type="text" class="form-control" id="Id" asp-for="BlogPost.Id" readonly>
                </div>
                <div class="mb-3">
                    <label for="heading" class="form-label">Heading</label>
                    <input type="text" class="form-control" id="heading" asp-for="BlogPost.Heading">
                </div>
                <div class="mb-3">
                    <label for="pageTitle" class="form-label">Page Title</label>
                    <input type="text" class="form-control" id="pageTitle" asp-for="BlogPost.PageTitle">
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">Content</label>
                    <textarea class="form-control" id="content" asp-for="BlogPost.Content"></textarea>
                </div>
                <div class="mb-3">
                    <label for="Short Description" class="form-label">Short Description</label>
                    <input type="text" class="form-control" id="Short Description" asp-for="BlogPost.ShortDescription">
                </div>
                <div class="mb-3">
                    <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
                    <input type="file" id="featuredImageUpload" asp-for="FeaturedImage">
                    @if (Model.BlogPost.FeaturedImageUrl != null)
                    {
                        <img src="@Model.BlogPost.FeaturedImageUrl" id="featuredImageDisplay" style="display:block; width:300px;" />
                    }
                    else
                    {
                        <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />
                    }
                    
                </div>

                <div class="mb-3">
                    <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                    <input type="text" class="form-control" id="featuredImageUrl" asp-for="BlogPost.FeaturedImageUrl">
                </div>
                <div class="mb-3">
                    <label for="urlHandle" class="form-label">Url Handle</label>
                    <input type="text" class="form-control" id="urlHandle" asp-for="BlogPost.UrlHandle">
                </div>
                <div class="mb-3">
                    <label for="publishedDate" class="form-label">Published Date</label>
                    <input type="date" class="form-control" id="publishedDate" asp-for="BlogPost.PublishedDate">
                </div>
                <div class="mb-3">
                    <label for="author" class="form-label">Author</label>
                    <input type="text" class="form-control" id="author" asp-for="BlogPost.Author">
                </div>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                    <label class="form-check-label" for="isVisible">
                        Is Visible
                    </label>
                </div>
                <div class="mb-3  d-flex justify-content-between">
                    <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>

                    <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
                </div>
            </form>
        </div>
    </div>

}

else
{
    <div class="container">
        <p>No Blog Post were found!</p>
    </div>    
}

@section Scripts {
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/image'
        });
        const featuredImageUploadElement = document.getElementById("featuredImageUpload");
        const featuredImageUrl = document.getElementById('featuredImageUrl');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay');

        async function uploadFeatureImage(e) {

            console.log(e.target.files[0]);
            let data = new FormData();
            data.append('file', e.target.files[0]);
            await fetch('/api/image', {
                method: 'POST',
                headers: {
                    Accept: '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageUrl.value = result.link;
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link;
                });
        }
        featuredImageUploadElement.addEventListener('change', uploadFeatureImage);
        console.log("this is outside");
    </script>
}

Bloggie/Pages/Admin/Blogs/List.cshtml
@page
@model Bloggie.Pages.Admin.Blogs.ListModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Blog Posts</h1>
    </div>
</div>

@* @{
    var messageDescription = (string)ViewData["MessageDescription"];
    // since viewData is of object type we are converting it explicitly to string type so that we
    //easily check whether it is null or empty bystring.IsNullOrEmpty
}

@if (!string.IsNullOrEmpty(messageDescription))
{
    <div class="alert alert-success alert-dismissible fade show mb-5" role="alert">
        @Html.Raw(messageDescription)
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
} *@

<partial name="_Notification"></partial>

@if (Model.BlogPosts != null && Model.BlogPosts.Any())
{
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Heading</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model.BlogPosts)
                {
                    <tr>
                        <td>@i.Id</td>
                        <td>@i.Heading</td>
                        <td><a href="/Admin/Blogs/Edit/@i.Id">view</a></td>
                        @* see when we press view it should be redirected to the Edit page so we did href="/Admin/Blogs/Edit now in the Edit page we
                want to only populate data of that particular Id only , so we need to pass Id as a route parameter,so to pass it as
                route parameter we did href="/Admin/Blogs/Edit/@i.Id"
                *@
                    </tr>
                }
                @*  here we can't do @foreach(var i in BlogPosts)
            it will throw error The name 'BlogPosts' does not exist in the current context, the reason for this error is
            In Razor views, properties and methods from the page model (the ListModel class in this case) are accessed through
            the Model property. This means you need to use Model.BlogPosts instead of just BlogPosts.

            It means if we want to access any property of code behind file in our razor view that we have to write Model.property_name

            *@
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container">
        <p>No Blog Post were found!</p>
    </div>
}




@* the List razor page is used for Reading data from database that is perform R in CRUD *@

Bloggie/Pages/Admin/Blogs/trial.cshtml
	@page "/home"
	@model Bloggie.Pages.Admin.Blogs.trialModel
	@{
		var htmlContent = "<b>This is bold text</b>";
	}
	<p>@htmlContent</p>
	<p><span>This is inside Html raw tag</span>@Html.Raw(htmlContent)</p>
	<b>This is bold text using b tag</b>